### PR TITLE
increase participants counter only if user does not have a cookie already

### PR DESCRIPTION
**Pull request by mnacos**
If you increase the participants count on every impression/view you are not really tracking the effectiveness of a given alternative. For example, person A visits index page and gets served alternative 1, and signs up immediately (1 participant, 1 conversion). Person B visits index page, gets served alternative 2, browses the web site a little more, goes back to the index page (still seeing alternative 2), is not sure, browses around some more, goes back to the index page then signs up (3 participants, 1 conversion). It seems wrong. People have different browsing habits.

Besides this, bandit is a great!

thanks,

Michael

### CODE REVIEW

**Comment by doolin** [comment]
+1

**Comment by bmuller** [comment]
Wow - so sorry this slipped under my radar. I'm going to take a look tomorrow morning and merge.

**Comment by bmuller** [comment]
Thanks for these changes! I just pushed and bumped the gem version on rubygems.

**Comment by mnacos** [comment]
You are welcome. Thanks for merging.

**Pull request closed without merging**
